---
- name: install and start ntp
  hosts: hosts_usa
  remote_user: "{{ uservar }}"
  sudo: true
  sudo_user: root
  
  tasks:
  - name: install ntp
    yum: name=ntp state=present
  
  - name: write the ntpd.conf file
    template: src=/opt/ansible-core/ansible/work/template/ntp.conf.j2 dest=/etc/ntpd.conf
    notify:
    - restart ntpd
    
  - name: start ntpd
    service: name=ntpd state=running
    
  handlers:
    - name: restart ntpd
      service: name=ntpd start=restarted
...      
